AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MyTestUserName1:
    Type: String
    Default: 'S3_test_user1'
  Password:
    Default: 'alex1234'
    Type: String
    Description: New account password
    MinLength: '1'
    MaxLength: '41'
    ConstraintDescription: the password must be between 1 and 41 characters
Resources:
  S3HomeBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3HomeBucket
                - /*
      Bucket: !Ref S3HomeBucket
  S3TestUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Join [ '-', [!Ref 'AWS::StackName',!Ref 'MyTestUserName1']]
      LoginProfile:
        Password: !Ref 'Password'
  S3UserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Join [ '-', [!Ref 'AWS::StackName','UserGroup']] 
  AddUsersToGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'S3UserGroup'
      Users: [!Ref 'S3TestUser']
  S3HomeUserPolicies:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: S3HomeUserLimit
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation','s3:ListAllMyBuckets']
          Resource: "*"
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: "arn:aws:s3:::*"
        - Effect: Allow
          Action: ['s3:GetObject','s3:PutObject','s3:DeleteObject']
          Resource: !Join ['', ['arn:aws:s3:::', !Ref 'S3HomeBucket','/home/${aws:username}/*']]
      Groups: [!Ref 'S3UserGroup']
  S3TestUserKeys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'S3TestUser'
Outputs:
  AccessKey:
    Value: !Ref 'S3TestUserKeys'
    Description: AWSAccessKeyId of new user
  SecretKey:
    Value: !GetAtt [S3TestUserKeys, SecretAccessKey]
    Description: AWSSecretKey of new user
  WebsiteURL:
    Value: !GetAtt 
      - S3HomeBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  StackName:
    Value: !Ref 'AWS::StackName'
    Description: StackName
  S3HomeBucketArn:
    Value: !Join ['', ['arn:aws:s3:::', !Ref 'S3HomeBucket']]
  S3HomeBucketArnHome:
    Value: !Join ['', ['arn:aws:s3:::', !Ref 'S3HomeBucket', '/home']]
  S3HomeBucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - S3HomeBucket
          - DomainName
    Description: Name of S3 bucket to hold website content
